### ISSUE TITLE
TypeError: Expected binary or unicode string, got None

### ISSUE THREAD

**Issue by ydhongHIT** [HiKapok/SSD.TensorFlow#103]
Traceback (most recent call last):
  File "train_ssd.py", line 464, in <module>
    tf.app.run()
  File "/home/xingkong/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_ssd.py", line 460, in main
    hooks=[logging_hook], max_steps=FLAGS.max_number_of_steps)
  File "/home/xingkong/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/xingkong/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/xingkong/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1154, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/xingkong/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/xingkong/.local/lib/python3.5/site-packages/tensorflow_estimator/contrib/estimator/python/estimator/replicate_model_fn.py", line 225, in single_device_model_fn
    local_ps_devices=ps_devices)[0]  # One device, so one spec is out.
  File "/home/xingkong/.local/lib/python3.5/site-packages/tensorflow_estimator/contrib/estimator/python/estimator/replicate_model_fn.py", line 566, in _get_loss_towers
    **optional_params)
  File "train_ssd.py", line 403, in ssd_model_fn
    scaffold=tf.train.Scaffold(init_fn=get_init_fn()))
  File "train_ssd.py", line 158, in get_init_fn
    name_remap={'/kernel': '/weights', '/bias': '/biases'})
  File "/home/xingkong/SSD-simple/utility/scaffolds.py", line 66, in get_init_fn_for_scaffold
    reader = tf.train.NewCheckpointReader(checkpoint_path)
  File "/home/xingkong/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 326, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/home/xingkong/.local/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

I try to run the program on my computer,but I encounter a problem. I don't how to solve it.

**Comment by ydhongHIT** [comment]
I solved the problem. I lose a file named 'checkpoint'. Thank for your contribution.

**Comment by yangjiao123** [comment]
Hi, I had the same problem. Could you tell me the details about how to solve the problem? Thank you very much.
