### ISSUE TITLE
TypeError: `default_name` type (<class 'list'>) is not a string type. When run train_ssd.py, I meet a TpyeError.

### ISSUE THREAD

**Issue by CaptainKeer** [HiKapok/SSD.TensorFlow#117]
tensorflow 1.14 ,python3.5 ,cuda10.0, cudnn7.5.0

Traceback (most recent call last):
  File "/home/wzy/SSD.TensorFlow-master/train_ssd.py", line 464, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/wzy/SSD.TensorFlow-master/train_ssd.py", line 460, in main
    hooks=[logging_hook], max_steps=FLAGS.max_number_of_steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1185, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1022, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1113, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/wzy/SSD.TensorFlow-master/train_ssd.py", line 198, in input_fn
    is_training=is_training)
  File "/home/wzy/SSD.TensorFlow-master/dataset/dataset_common.py", line 231, in slim_get_batch
    gt_targets, gt_labels, gt_scores = anchor_encoder(glabels, gbboxes)
  File "/home/wzy/SSD.TensorFlow-master/train_ssd.py", line 187, in <lambda>
    anchor_encoder_fn = lambda glabels_, gbboxes_: anchor_encoder_decoder.encode_all_anchors(glabels_, gbboxes_, all_anchors, all_num_anchors_depth, all_num_anchors_spatial)
  File "/home/wzy/SSD.TensorFlow-master/utility/anchor_manipulator.py", line 177, in encode_all_anchors
    overlap_matrix = iou_matrix(bboxes, anchors_point) * tf.cast(tf.expand_dims(inside_mask, 0), tf.float32)
  File "/home/wzy/SSD.TensorFlow-master/utility/anchor_manipulator.py", line 43, in iou_matrix
    with tf.name_scope('iou_matrix', [gt_bboxes, default_bboxes]):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 6450, in __init__
    "pass this into the `values` kwarg." % type(default_name))
TypeError: `default_name` type (<class 'list'>) is not a string type. You likely meant to pass this into the `values` kwarg.

**Comment by maidouxiaozi** [comment]
I have the same problem

**Comment by tinothy22** [comment]
I have same problem,do you solve?

**Comment by 18846935350** [comment]
查找tf.name_cope()，将[Image]更改为values=[Image]，即Add values=

**Comment by tinothy22** [comment]
sorry, i can't find it,can you be more detailed?

**Comment by 18846935350** [comment]
Search for name_scope in train_ssd.py. It should be 213 lines. Change name scope ("", []) to name scope ("", values = []).







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tinothy22"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 下午2:10
收件人: "HiKapok/SSD.TensorFlow"<SSD.TensorFlow@noreply.github.com&gt;; 
抄送: "小太阳"<18846935350@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HiKapok/SSD.TensorFlow] TypeError: `default_name` type (<class &#39;list&#39;&gt;) is not a string type. When run train_ssd.py, I meet a TpyeError. (#117)




sorry, i can't find it,can you be more detailed?

**Comment by tinothy22** [comment]
still the same mistake

**Comment by tinothy22** [comment]
i have solve,change all name_scope in anchor_manipulator.py

**Comment by 18846935350** [comment]
That's good. I just corrected this mistake the other day.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tinothy22"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 晚上7:12
收件人: "HiKapok/SSD.TensorFlow"<SSD.TensorFlow@noreply.github.com&gt;; 
抄送: "小太阳"<18846935350@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HiKapok/SSD.TensorFlow] TypeError: `default_name` type (<class &#39;list&#39;&gt;) is not a string type. When run train_ssd.py, I meet a TpyeError. (#117)




i have solve,change all name_scope in anchor_manipulator.py

**Comment by lambozhang** [comment]
I have same problem, What should I do

**Comment by jenweilee** [comment]
> i have solve,change all name_scope in anchor_manipulator.py

what the details you did?
