### ISSUE TITLE
voc_eval.py on my own dataset

### ISSUE THREAD

**Issue by Kasyene** [HiKapok/SSD.TensorFlow#120]
Hello,
I introduced my own dataset with 1 real class + background class.
My dataset is in voc-like format.
I trained it, I can test it and it detects trained class without any problems. 
The eval_ssd.py generates the results file. The problem I have is with voc_eval.py to measure map for my class.

```
VOC07 metric? Yes
Traceback (most recent call last):
  File "voc_eval.py", line 268, in <module>
    do_python_eval()
  File "voc_eval.py", line 79, in do_python_eval
    ovthresh=0.5, use_07_metric=use_07_metric)
  File "voc_eval.py", line 221, in voc_eval
    R = class_recs[image_ids[d]]
KeyError: '0594'
```

I am not sure if I understand what test.txt should contain and how to fix this issue.
I attatched files with my dataset and result.txt I got from eval_ssd. test.txt attatched is the original one - with 1st error.

[trainval.txt](https://github.com/HiKapok/SSD.TensorFlow/files/3554648/trainval.txt)
[val.txt](https://github.com/HiKapok/SSD.TensorFlow/files/3554649/val.txt)
[test.txt](https://github.com/HiKapok/SSD.TensorFlow/files/3554651/test.txt)
[train.txt](https://github.com/HiKapok/SSD.TensorFlow/files/3554652/train.txt)
[results_1.txt](https://github.com/HiKapok/SSD.TensorFlow/files/3554656/results_1.txt)

Edit: I assumed the probem was that file 0594 was in result file and not in the test.txt.  So I tried replacing file names in test.txt with all the names in results.txt (without duplicates) and it works now. I am still unsure because I was sure test.txt should contain different set of files.

Can you please help? It seems I am misunderstading something completely.

**Comment by tristehai** [comment]
How did you solve this problem
