### ISSUE TITLE
ERROR:Expected binary or unicode string, got None

### ISSUE THREAD

**Issue by yang1015661763** [HiKapok/SSD.TensorFlow#121]
Traceback (most recent call last):
  File "train_ssd.py", line 464, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.
py", line 125, in run
    _sys.exit(main(argv))
  File "train_ssd.py", line 460, in main
    hooks=[logging_hook], max_steps=FLAGS.max_number_of_steps)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\est
imator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\est
imator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\est
imator.py", line 1211, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\est
imator.py", line 1169, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\estimator\py
thon\estimator\replicate_model_fn.py", line 225, in single_device_model_fn
    local_ps_devices=ps_devices)[0]  # One device, so one spec is out.
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\estimator\py
thon\estimator\replicate_model_fn.py", line 566, in _get_loss_towers
    **optional_params)
  File "train_ssd.py", line 403, in ssd_model_fn
    scaffold=tf.train.Scaffold(init_fn=get_init_fn()))
  File "train_ssd.py", line 158, in get_init_fn
    name_remap={'/kernel': '/weights', '/bias': '/biases'})
  File "D:\jupyter\04HiKapok_ssd_tf\utility\scaffolds.py", line 66, in get_init_fn
_for_scaffold
    reader = tf.train.NewCheckpointReader(checkpoint_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensor
flow_internal.py", line 314, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\compat.p
y", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

**Comment by navy63** [comment]
The same problem

**Comment by navy63** [comment]
这个原因我找到了，这个版本VGG16和balancap版本的VGG不同，需要在作者这里的百度云链接中重新下载，下载完了就可以了。
