### ISSUE TITLE
eval error

### ISSUE THREAD

**Issue by jiawensong** [HiKapok/SSD.TensorFlow#20]
after i download your file and checkpoint ,then i run the eval.py, it give out error like this.
C:\Users\DELL\PycharmProjects\unstructured_data\venv\Scripts\python.exe D:/git_code/SSD.TensorFlow/eval_ssd.py
INFO:tensorflow:Using config: {'_model_dir': './logs/', '_tf_random_seed': None, '_save_summary_steps': 500, '_save_checkpoints_steps': None, '_save_checkpoints_secs': None, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 10, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000002B7C3A76F98>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
Starting a predict cycle.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From D:\git_code\SSD.TensorFlow\net\ssd_net.py:114: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
2018-06-28 21:01:10.495852: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
INFO:tensorflow:Restoring parameters from ./model\vgg16_reducedfc.ckpt
2018-06-28 21:01:10.574406: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key global_step not found in checkpoint
Traceback (most recent call last):
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key global_step not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/git_code/SSD.TensorFlow/eval_ssd.py", line 456, in <module>
    tf.app.run()
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "D:/git_code/SSD.TensorFlow/eval_ssd.py", line 427, in main
    det_results = list(pred_results)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\estimator\estimator.py", line 507, in predict
    hooks=all_hooks) as mon_sess:
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 816, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 539, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1002, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1007, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 696, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 467, in create_session
    init_fn=self._scaffold.init_fn)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\session_manager.py", line 279, in prepare_session
    config=config)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\session_manager.py", line 191, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key global_step not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "D:/git_code/SSD.TensorFlow/eval_ssd.py", line 456, in <module>
    tf.app.run()
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "D:/git_code/SSD.TensorFlow/eval_ssd.py", line 427, in main
    det_results = list(pred_results)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\estimator\estimator.py", line 507, in predict
    hooks=all_hooks) as mon_sess:
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 816, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 539, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1002, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1007, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 696, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 458, in create_session
    self._scaffold.finalize()
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 212, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\saver.py", line 910, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1338, in __init__
    self.build()
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\saver.py", line 829, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\saver.py", line 525, in _AddShardedRestoreOps
    name="restore_shard"))
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\saver.py", line 472, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\training\saver.py", line 886, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1546, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\Users\DELL\PycharmProjects\unstructured_data\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key global_step not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Process finished with exit code 1

**Comment by HiKapok** [comment]
@jiawensong please make sure that you were using the right version of tensorflow, by the way, did you test the codes under Ubuntu?

**Comment by jiawensong** [comment]
i want to debug under my windows computer, and it can run correctly in ubuntu now. And i have another question, i couldn't find data loading api in train_ssd.py

**Comment by HiKapok** [comment]
@jiawensong What did you mean by data loading api? all the data preprocessing operations are in 'input_fn'

**Comment by jiawensong** [comment]
yeah, i have seen that function, i am trying to train by my own data, thanks for your help
