### ISSUE TITLE
a problem meet during training my own data

### ISSUE THREAD

**Issue by jiawensong** [HiKapok/SSD.TensorFlow#21]
i have modified convert_tfrecords.py to produce my own *.tfrecords. My xml file is constructed like this.
![image](https://user-images.githubusercontent.com/20223238/42263379-75b5f82c-7fa0-11e8-9693-c04516504586.png)
when i start traning , i have met problem, and information on console is like this.
ssh://jiawen@39.104.161.150:22/home/jiawen/anaconda3/envs/mnist_test/bin/python3.5 -u /home/jiawen/gitcode/ssd.tensorflow/train_ssd.py
2018-07-04 15:41:59.453717: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-07-04 15:41:59.962936: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-04 15:41:59.964121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:00:08.0
totalMemory: 15.90GiB freeMemory: 15.61GiB
2018-07-04 15:41:59.964159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-04 15:42:00.289100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-04 15:42:00.289164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-04 15:42:00.289179: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-04 15:42:00.289601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/device:GPU:0 with 15135 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:08.0, compute capability: 6.0)
INFO:tensorflow:Replicating the `model_fn` across ['/device:GPU:0'].  Variables are going to be placed on ['/device:GPU:0'].  Consolidation device is going to be /device:GPU:0.
INFO:tensorflow:Using config: {'_task_type': 'worker', '_num_worker_replicas': 1, '_evaluation_master': '', '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f931a6ca630>, '_keep_checkpoint_every_n_hours': 10000, '_task_id': 0, '_log_step_count_steps': 10, '_global_id_in_cluster': 0, '_save_summary_steps': 500, '_tf_random_seed': 20180503, '_model_dir': './logs/', '_save_checkpoints_secs': 7200, '_service': None, '_save_checkpoints_steps': None, '_train_distribute': None, '_master': '', '_keep_checkpoint_max': 5, '_num_ps_replicas': 0, '_is_chief': True, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
allow_soft_placement: true
}
Starting a training cycle.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /home/jiawen/gitcode/ssd.tensorflow/net/ssd_net.py:114: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
INFO:tensorflow:Fine-tuning from ./model/vgg16_reducedfc.ckpt. Ignoring missing vars: True.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-07-04 15:42:05.769670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-04 15:42:05.769732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-04 15:42:05.769749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-04 15:42:05.769763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-04 15:42:05.769994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15135 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:08.0, compute capability: 6.0)
INFO:tensorflow:Restoring parameters from ./model/vgg16_reducedfc.ckpt
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
2018-07-04 15:42:13.305340: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: flat indices[30, :] = [30, -1] does not index into param (shape: [32,6792]).
Traceback (most recent call last):
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[30, :] = [30, -1] does not index into param (shape: [32,6792]).
	 [[Node: post_forward/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](post_forward/TopKV2, post_forward/stack)]]
	 [[Node: post_forward/boolean_mask/Squeeze/_691 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_653_post_forward/boolean_mask/Squeeze", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiawen/gitcode/ssd.tensorflow/train_ssd.py", line 464, in <module>
    tf.app.run()
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/jiawen/gitcode/ssd.tensorflow/train_ssd.py", line 460, in main
    hooks=[logging_hook], max_steps=FLAGS.max_number_of_steps)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 859, in _train_model_default
    saving_listeners)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1059, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 567, in run
    run_metadata=run_metadata)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1043, in run
    run_metadata=run_metadata)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1134, in run
    raise six.reraise(*original_exc_info)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1119, in run
    return self._sess.run(*args, **kwargs)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1191, in run
    run_metadata=run_metadata)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 971, in run
    return self._sess.run(*args, **kwargs)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[30, :] = [30, -1] does not index into param (shape: [32,6792]).
	 [[Node: post_forward/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](post_forward/TopKV2, post_forward/stack)]]
	 [[Node: post_forward/boolean_mask/Squeeze/_691 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_653_post_forward/boolean_mask/Squeeze", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'post_forward/GatherNd', defined at:
  File "/home/jiawen/gitcode/ssd.tensorflow/train_ssd.py", line 464, in <module>
    tf.app.run()
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/jiawen/gitcode/ssd.tensorflow/train_ssd.py", line 460, in main
    hooks=[logging_hook], max_steps=FLAGS.max_number_of_steps)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 856, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/jiawen/gitcode/ssd.tensorflow/tf_replicate_model_fn.py", line 201, in single_device_model_fn
    local_ps_devices=ps_devices)[0]  # One device, so one spec is out.
  File "/home/jiawen/gitcode/ssd.tensorflow/tf_replicate_model_fn.py", line 534, in _get_loss_towers
    **optional_params)
  File "/home/jiawen/gitcode/ssd.tensorflow/train_ssd.py", line 321, in ssd_model_fn
    score_at_k = tf.gather_nd(topk_prob_for_bg, tf.stack([tf.range(tf.shape(features)[0]), batch_n_neg_select - 1], axis=-1))
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2975, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/jiawen/anaconda3/envs/mnist_test/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): flat indices[30, :] = [30, -1] does not index into param (shape: [32,6792]).
	 [[Node: post_forward/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](post_forward/TopKV2, post_forward/stack)]]
	 [[Node: post_forward/boolean_mask/Squeeze/_691 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_653_post_forward/boolean_mask/Squeeze", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Process finished with exit code 1

**Comment by HiKapok** [comment]
@jiawensong try to filter images those have zero bbox, by the way, can you train PASCAL VOC successfully?

**Comment by franklu323** [comment]
![default](https://user-images.githubusercontent.com/28680833/42268085-c6b56cf2-7fce-11e8-96c5-492755cdb46b.JPG)
I think we met the same problem. I use my own dataset which followed by the VOC format, and convert was fine (I think, cause I ran 'inspect' after, and train samples, val samples it matches). But when I train the model, the error occurs. I also received this 'InvalidArgumentError (see above for traceback): flat indices[30, :] = [30, -1] does not index into param (shape: [32,6792]).'

**Comment by HiKapok** [comment]
@franklu323 did you change your batch_size? Hope you can check if there is images that have no bbox with them, And also thanks for you issue report.

**Comment by franklu323** [comment]
@HiKapok I do change my batch size to 4, cause my GPU is GTX1060 and I also change the number of classes to 5 (cause I only have 5 classes).

**Comment by HiKapok** [comment]
@franklu323 did you also used tensorflow1.4?

**Comment by HiKapok** [comment]
@jiawensong what did you mean by 'haven't create negative boundingbox', did you have one class for background?

**Comment by jiawensong** [comment]
@HiKapok i have just create two class, number and chinese character, i haven't create class for background

**Comment by HiKapok** [comment]
@jiawensong @franklu323 both of your problems should caused by this line of [code](https://github.com/HiKapok/SSD.TensorFlow/blob/dd910d6643556bc236113f99d116e61c083b8b30/train_ssd.py#L321) when there is image's 'batch_n_neg_select' equals 0, this only can be caused by the zero positives, so I guess there maybe some image have no bbox with them

**Comment by HiKapok** [comment]
@jiawensong background class is needed in any detection task

**Comment by jiawensong** [comment]
@HiKapok oh, maybe the problem is that i set number class with 0 label, then the program take number class as negative example, when some xml files without chinese character taken as input , the number of positive example is set to 0 and batch_n_neg_select equals 0.

**Comment by franklu323** [comment]
@HiKapok So do I need to label the background or just in data_common.py, set background as 0 and the rest of them are my own data classes??

**Comment by HiKapok** [comment]
@franklu323 @jiawensong you needn't label background class, just follow the original pascal dataset's setting, leave one placeholder of value '0' for background class, thanks for your issue report
