### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by woshilicong33** [HiKapok/SSD.TensorFlow#47]
运行完eeval_ssd,之后运行voc_eval,提示FileNotFoundError: [Errno 2] No such file or directory: '/media/streamax/disk1/DataSet/test-VOC-2012/VOCdevkit/VOC2012/Annotations/2008_000001.xml'

没有2008_0000001.xml啊

**Comment by HiKapok** [comment]
@woshilicong33 you cannot run evalation on 2012-test set, instead you should upload them inline to eval

**Comment by woshilicong33** [comment]
我换个2007
Traceback (most recent call last):
File "/home/streamax/Cong.L/SSD.TensorFlow-master/voc_eval.py", line 269, in
do_python_eval()
File "/home/streamax/Cong.L/SSD.TensorFlow-master/voc_eval.py", line 79, in do_python_eval
ovthresh=0.5, use_07_metric=use_07_metric)
File "/home/streamax/Cong.L/SSD.TensorFlow-master/voc_eval.py", line 222, in voc_eval
R = class_recs[image_ids[d]]
KeyError: '0.014'
出现这个错误

**Comment by woshilicong33** [comment]
可以读取
Reading annotation for 4301/4952
Reading annotation for 4401/4952
Reading annotation for 4501/4952
Reading annotation for 4601/4952
Reading annotation for 4701/4952
Reading annotation for 4801/4952
Reading annotation for 4901/4952
Saving cached annotations to ./logs_224/predict2/eval_cache/annots.pkl

Traceback (most recent call last):
  File "/home/streamax/Cong.L/SSD.TensorFlow-master/voc_eval.py", line 271, in <module>
    do_python_eval()
  File "/home/streamax/Cong.L/SSD.TensorFlow-master/voc_eval.py", line 77, in do_python_eval
    rec, prec, ap = voc_eval(filename, os.path.join(dataset_path, anno_files), os.path.join(dataset_path, all_images_file), cls_name, cache_path,ovthresh=0.5, use_07_metric=use_07_metric)
  File "/home/streamax/Cong.L/SSD.TensorFlow-master/voc_eval.py", line 224, in voc_eval
    R = class_recs[image_ids[d]]
KeyError: '0.020'

**Comment by HiKapok** [comment]
@woshilicong33 你用仓库里提供的convert_tfrecords，什么都别改，只改路径肯定没问题的，很多人都试过了，耐心找找问题吧

**Comment by woshilicong33** [comment]
好的，谢谢，我是用的我自己生成的tfrecords,或许问题出在这里
