### ISSUE TITLE
同学  我在对你的SSD的代码做了一些改进的基础上（主要是改成Textboxes），训练synthtext数据集，现在报了一个错

### ISSUE THREAD

**Issue by moooood** [HiKapok/SSD.TensorFlow#77]
`Traceback (most recent call last):
 60   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
 61     return fn(*args)
 62   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
 63     options, feed_dict, fetch_list, target_list, run_metadata)
 64   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
 65     run_metadata)
 66 tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[7, :] = [7, -1] does not index into param (shape: [16,27160]).
 67      [[Node: post_forward/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](post_forward/TopKV2, post_forward/stack)]]
 69 
 70 During handling of the above exception, another exception occurred:
 71 
 72 Traceback (most recent call last):
 73   File "train_textboxes.py", line 547, in <module>
 74     tf.app.run()
 75   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
 76     _sys.exit(main(argv))
 77   File "train_textboxes.py", line 542, in main
 78     hooks=[logging_hook], max_steps=FLAGS.max_number_of_steps)
 79   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 366, in train
 80     loss = self._train_model(input_fn, hooks, saving_listeners)
 81   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1119, in _train_model
 82     return self._train_model_default(input_fn, hooks, saving_listeners)
 83   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1135, in _train_model_default
 84     saving_listeners)
 85   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1336, in _train_with_estimator_spec
 86     _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
 87   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 577, in run
 88     run_metadata=run_metadata)
 89   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1053, in run
 90     run_metadata=run_metadata)
 91   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1144, in run
 92     raise six.reraise(*original_exc_info)
 93   File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
 94     raise value
 95   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1129, in run
 96     return self._sess.run(*args, **kwargs)
 97   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1201, in run
 98     run_metadata=run_metadata)
 99   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 981, in run
100     return self._sess.run(*args, **kwargs)
101   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
102     run_metadata_ptr)
105   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
106     run_metadata)
107   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
108     raise type(e)(node_def, op, message)
109 tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[7, :] = [7, -1] does not index into param (shape: [16,27160]).
110      [[Node: post_forward/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](post_forward/TopKV2, post_forward/stack)]]
111      [[Node: post_forward/boolean_mask/GatherV2/_1081 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", 
    send_device_incarnation=1, tensor_name="edge_1008_post_forward/boolean_mask/GatherV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
112 
113 Caused by op 'post_forward/GatherNd', defined at:
114   File "train_textboxes.py", line 547, in <module>
115     tf.app.run()
116   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
117     _sys.exit(main(argv))
118   File "train_textboxes.py", line 542, in main
119     hooks=[logging_hook], max_steps=FLAGS.max_number_of_steps)
120   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 366, in train
121     loss = self._train_model(input_fn, hooks, saving_listeners)
122   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1119, in _train_model
123     return self._train_model_default(input_fn, hooks, saving_listeners)
124   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1132, in _train_model_default
125     features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
126   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1107, in _call_model_fn
127     model_fn_results = self._model_fn(features=features, **kwargs)
128   File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/estimator/python/estimator/replicate_model_fn.py", line 225, in single_device_model_fn
129     local_ps_devices=ps_devices)[0]  # One device, so one spec is out.
130   File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/estimator/python/estimator/replicate_model_fn.py", line 566, in _get_loss_towers
131     **optional_params)
132   File "train_textboxes.py", line 390, in textboxes_model_fn
133     tf.stack([tf.range(batch), batch_n_neg_select - 1], axis=-1))
134   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3051, in gather_nd
135     "GatherNd", params=params, indices=indices, name=name)
136   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
137     op_def=op_def)
138   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
139     op_def=op_def)
140   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
141     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
142 
143 InvalidArgumentError (see above for traceback): flat indices[7, :] = [7, -1] does not index into param (shape: [16,27160]).
144      [[Node: post_forward/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](post_forward/TopKV2, post_forward/stack)]]
145      [[Node: post_forward/boolean_mask/GatherV2/_1081 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0",
    send_device_incarnation=1, tensor_name="edge_1008_post_forward/boolean_mask/GatherV2", tensor_type=DT_FLOAT, `_device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by moooood** [comment]
synthtext数据集的质量应该是很高的，是我在处理数据集的过程中出错了吗？原始的数据集中每张图片应该是都有GT的
